
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 22.1.0 - arm64
...
